version: "3"
services:
  api:
    build: api/
    container_name: api
    restart: on-failure:3
    ports:
      - 5000:5000
    depends_on:
      - db

  nginx:
    image: erangaeb/senznginx:0.4
    build: nginx/
    container_name: nginx
    restart: on-failure:3
    ports:
      - 80:80
    links:
      - api

  db:
    image: postgres:12-alpine
    container_name: database
    restart: on-failure:3
    environment:
      POSTGRES_USER: uhjrbye
      POSTGRES_PASSWORD: fZ5gd1PqRaBJdx9MUUW0H3KaswyE5_Oi
    volumes:
      - postgres_data:/var/lib/postgresql/data/



volumes:
  postgres_data:
